# Exlusions
exclude: ["Gemfile", "Gemfile.lock", "vendor", "node_modules", "gulpfile.js", "rsync.sh", "autoprefixer.yml"]
include: [".well-known"]

# Site settings
title: 'Boris Schapira'
tagline: 'Life is too short to be small'
email: borisschapira@gmail.com
description: "Blog personnel de Boris Schapira"
baseurl: ""
url: "http://borisschapira.com"
lang: fr

# Author
name: 'Boris Schapira'
author:
  name:           'Boris Schapira'
  url:            https://borisschapira.com/
  flickr: 'http://flickr.com/borisschapira'
  github: 'http://github.com/borisschapira'
  facebook: 'https://www.facebook.com/boris.schapira'
  twitter: 'http://twitter.com/borisschapira'
  linkedin: 'http://linkedin.com/in/borisschapira'
  feed: 'http://borisschapira.com/feed.xml'

# Formats
format_date: '%A %-d %B %Y'

# Writing configuration
markdown:    kramdown
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge

# Posts links and pagination
permalink:        :year/:month/:title
relative_permalinks: true
paginate:            5
paginate_path:       "/:num/"

# Tagging
tag_page_layout: tag
tag_page_dir: tags

sass:
  sass_dir: _scss
  style: :compressed

# Algolia
gems:
  - jekyll-sitemap
  - algoliasearch-jekyll
  - jekyll-archives
  - jekyll-picture-tag
  - jekyll-twitter-plugin
  - octopress-autoprefixer

algolia:
  application_id: '97EL687MDM'
  index_name: 'jekyll'
  read_only_api_key: '45e74dfb46facf8ee7f3038c305a9a7e'
  excluded_files:
    - 404.html
    - index.html

jekyll-archives:
  enabled:
    - "year"
    - "month"
  layouts:
    year: "archives-year"
    month: "archives-month"
  permalinks:
    year: "/:year/"
    month: "/:year/:month/"

picture:
  source: "assets/images"
  output: "assets/images/generated"
  markup: "picture"
  presets:
    default:
      ppi: [1, 2]
      source_640:
        media: "(min-width: 580px)"
        width: "640"
      source_530:
        media: "(min-width: 470px)"
        width: "530"
      source_430:
        media: "(min-width: 350px)"
        width: "430"
      source_default:
        width: "320"

twitter:
  consumer_key: 9JKsWYyRs3YmutyrTCLrBRxD7
  consumer_secret: cOsDNGzAcnCx17HYxBqkFclSD15VYsOu3mX9wuqS55ZZZCHIw9
  access_token: 10339172-k8oQMF4cH6kSph8UXuxvMFNaMIsfmur6uarxBHhIM
  access_token_secret: uekrSoSanv2Fk7X6T36H7RXeRCDl1cBGISeAnBjIdNvMz

youtube:
  api_key: AIzaSyCjxrXef176AuPxGHgBgi3OtkbzWkLpx70
