# Exlusions
exclude: ["Gemfile", "Gemfile.lock", "vendor", "node_modules", "gulpfile.js", "rsync.sh"]

# Site settings
title: 'Boris Schapira'
tagline: 'Life is too short to be small'
email: borisschapira@gmail.com
description:      'The popular <a href="http://hyde.getpoole.com/" target="_blank">Hyde theme</a> for <a href="http://jekyllrb.com" target="_blank">Jekyll</a>, now with instant-search capabilities. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a> and <a href="https://www.algolia.com/" target="_blank">Algolia</a>'
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://borisschapira.com" # the base hostname & protocol for your site

# Author
name: 'Boris Schapira'
author:
  name:           'Boris Schapira'
  url:            https://borisschapira.com/
  flickr: 'http://flickr.com/borisschapira'
  github: 'http://github.com/borisschapira'
  facebook: 'https://www.facebook.com/boris.schapira'
  twitter: 'http://twitter.com/borisschapira'
  linkedin: 'http://linkedin.com/in/borisschapira'

# Formats
format_date: '%A %-d %B %Y'

# Writing configuration
markdown:         kramdown
highlighter:      rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Posts links and pagination
permalink:        :year/:month/:title
relative_permalinks: true
paginate:         5

# Tagging
tag_page_layout: tag_page
tag_page_dir: tag

# Algolia
gems:
  - algoliasearch-jekyll
  - jekyll-archives
  - jekyll-picture-tag
  - jekyll-feed

algolia:
  application_id: '97EL687MDM'
  index_name: 'jekyll_dev'
  read_only_api_key: '45e74dfb46facf8ee7f3038c305a9a7e'
  excluded_files:
    - 404.html
    - index.html

jekyll-archives:
  enabled:
    - "year"
    - "month"
  layouts:
    year: "archives-year"
    month: "archives-month"
  permalinks:
    year: "/:year/"
    month: "/:year/:month/"

picture:
  source: "assets/images/_fullsize"
  output: "generated"
  markup: "picture"
  presets:
    default:
      ppi: [1, 2]
      source_640:
        media: "(min-width: 580px)"
        width: "640"
      source_530:
        media: "(min-width: 470px)"
        width: "530"
      source_430:
        media: "(min-width: 350px)"
        width: "430"
      source_default:
        width: "320"
