# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Exclusions
exclude: ["Gemfile", "Gemfile.lock", "vendor", "node_modules", "scripts", "autoprefixer.yml"]
include: [".well-known", ".htaccess"]

# Site settings
name: 'Boris Schapira'
title: 'Boris Schapira'
email: borisschapira@gmail.com
tagline: 'Life is too short to be small'
description: "Blog personnel de Boris Schapira"
baseurl: ""
url: "https://borisschapira.com"
lang: fr

# Author
name: 'Boris Schapira'
author:
  name:           'Boris Schapira'
  url:            https://borisschapira.com/
  flickr: 'http://flickr.com/borisschapira'
  github: 'http://github.com/borisschapira'
  facebook: 'https://www.facebook.com/boris.schapira'
  twitter: 'http://twitter.com/borisschapira'
  linkedin: 'http://linkedin.com/in/borisschapira'
  feed: 'http://borisschapira.com/feed.xml'

# Build settings
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge

# Posts links and pagination
permalink: :year/:month/:title/

# EU Cookie law
eu_cookie_law:
  active: true
  more_url: http://blog.temesis.com/post/2015/02/16/Cookies-le-grand-bug

gems:
  - jekyll-assets
  - jekyll-sitemap
  - jekyll-archives
  - algoliasearch-jekyll
  - jekyll-paginate
  - octopress-autoprefixer
  - octopress-debugger

jekyll-archives:
  enabled:
    - "year"
    - "month"
  layouts:
    year: "archives-year"
    month: "archives-month"
  permalinks:
    year: "/:year/"
    month: "/:year/:month/"

# Tagging
# tag_page_layout: tag
# tag_page_dir: tags
# tag_permalink_style: pretty

# Pagination
paginate: 5
paginate_path: "/:num/"

assets:
  prefix: "/assets"
  sources:
    - _assets/scripts
    - _assets/styles
  js_compressor:  "uglifier"
  css_compressor: "scss"

responsive_image:
  # [Required]
  # Path to the image template.
  template: _includes/responsive-image.html

  # [Optional, Default: 85]
  # Quality to use when resizing images.
  default_quality: 90

  # [Optional, Default: []]
  # An array of resize configuration objects. Each object must contain at least
  # a `width` value.
  sizes:
    - width: 320  # [Required] How wide the resized image will be.
      quality: 80 # [Optional] Overrides default_quality for this size.
    - width: 640

  # [Optional, Default: assets]
  # Use this parameter if your images are stored in subfolders
  # and you want to keep the folder arrangement
  base_path: assets/images

  # [Optional, Default: assets/resized/%{filename}-%{width}x%{height}.%{extension}]
  # The template used when generating filenames for resized images. Must be a
  # relative path.
  #
  # Parameters available are:
  #   %{basename}    Basename of the file (assets/some-file.jpg => some-file.jpg)
  #   %{filename}    Basename without the extension (assets/some-file.jpg => some-file)
  #   %{extension}   Extension of the file (assets/some-file.jpg => jpg)
  #   %{width}       Width of the resized image
  #   %{height}      Height of the resized image
  #
  output_path_format: assets/resized/%{folderpath}/%{width}/%{basename}
